# Configurarea serverului virtual Nginx
server {
    # Îi spunem lui Nginx să asculte pe portul standard HTTP 80 în interiorul containerului
    listen 80;

    # Definim regulile pentru ruta principală ("/") și toate sub-rutele site-ului
    location / {
        # PROXY_PASS: Directiva magică! Ia orice cerere venită de la utilizator (pe portul 80)
        # și o trimite (o passează) către containerul Flask numit 'flask-app' pe portul său intern 5000
        proxy_pass http://flask-app:5000;
        
        # Trimite mai departe către Flask antetul (header-ul) original 'Host' primit de la utilizator
        # Ajută Flask-ul să știe ce adresă de site a tastat omul în browser
        proxy_set_header Host $host;
        
        # Trimite IP-ul real al vizitatorului către aplicația Flask
        # Fără linia asta, Flask ar crede că toate cererile vin doar de la proxy-ul Nginx, nu de la oameni reali
        proxy_set_header X-Real-IP $remote_addr;
    }
}